wip: updated the pipeline workflow file

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -22,32 +22,35 @@ jobs:
       - name: Install dependencies
         run: yarn install
 
+      - name: Run Tests
+        run: yarn test
+
       - name: Run Build
         run: yarn build
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-      - name: Deploy to server
-        uses: easingthemes/ssh-deploy@main
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
-          REMOTE_HOST: ${{ secrets.HOST_DNS }}
-          REMOTE_USER: ${{ secrets.USERNAME }}
-          TARGET: ${{ secrets.TARGET_DIR }}
+  # deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   steps:
+  #     - name: Deploy to server
+  #       uses: easingthemes/ssh-deploy@main
+  #       env:
+  #         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
+  #         REMOTE_HOST: ${{ secrets.HOST_DNS }}
+  #         REMOTE_USER: ${{ secrets.USERNAME }}
+  #         TARGET: ${{ secrets.TARGET_DIR }}
 
-      - name: Executing remote ssh commands using ssh key
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            sudo apt-get -y update
-            sudo apt-get install -y apache2
-            sudo systemctl start apache2 || { echo "Failed to start Apache2"; exit 1; }
-            sudo systemctl enable apache2 || { echo "Failed to enable Apache2"; exit 1; }
-            cd /var/www/html
-            sudo rm -rf *
-            sudo mv /home/* .
+  #     - name: Executing remote ssh commands using ssh key
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.HOST_DNS }}
+  #         username: ${{ secrets.USERNAME }}
+  #         key: ${{ secrets.EC2_SSH_KEY }}
+  #         script: |
+  #           sudo apt-get -y update
+  #           sudo apt-get install -y apache2
+  #           sudo systemctl start apache2 || { echo "Failed to start Apache2"; exit 1; }
+  #           sudo systemctl enable apache2 || { echo "Failed to enable Apache2"; exit 1; }
+  #           cd /var/www/html
+  #           sudo rm -rf *
+  #           sudo mv /home/* .
